# SITE SETTINGS
title:                "Minus K Technology"
subtitle:             "Vibration Isolation Platform & Table Systems | Isolators, Platforms & Tables"
email:                Email here
author:               Name Here
description:          "Vibration isolation platform & table systems, isolator platforms, tables & benches. Our anti-vibration technologies, vibration control isolators & isolation table products offer the best devices among companies & manufacturers of anti vibration equipment."
baseurl:              "" # subpath if necessary, e.g. /blog/
url:                  "" # base url http://url.com

# GOOGLE ANALYTICS
google_analytics:     UA-XXXXX-X

# BUILD SETTINGS
markdown:             kramdown
permalink:            pretty
paginate:             3
sass:
  sass_dir:           /assets/_sass/
  compressed:         true

# FEATURE SETS
show_related_posts:   false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# SOCIAL
show_social:          false
github_username:
twitter_username:
linkedin_username:
flattr_button:

# Post sharing icons
show_sharing:         false
share_text:           'Share this post!'
# Change to 'true' to enable individual icons
share_facebook:       false
share_twitter:        false
share_googleplus:     false
share_linkedin:       false
share_digg:           false
share_tumblr:         false
share_reddit:         false
share_stumbleupon:    false
share_hackernews:     false

# GEMS
gems:
  - jekyll-sitemap